version: '3.9'
services:

  postgres:
    container_name: postgres
    image: postgres:14
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: 'postgres'
      POSTGRES_USER: 'wallet-user'
      POSTGRES_PASSWORD: '12345'
      POSTGRES_DB: 'postgres'
    ports:
      - 5432:5432

  app:
    build: .
    container_name: app
    image: app
    environment:
      PG_URL: 'postgres://wallet-user:12345@postgres:5432/postgres'
    ports:
      - 80:80
    depends_on:
      - postgres

volumes:
  pg-data:
