// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/svbnbyrk/wallet/internal/entity"
)

// WalletRepository is an autogenerated mock type for the WalletRepository type
type WalletRepository struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, id
func (_m *WalletRepository) Get(ctx context.Context, id int64) (entity.Wallet, error) {
	ret := _m.Called(ctx, id)

	var r0 entity.Wallet
	if rf, ok := ret.Get(0).(func(context.Context, int64) entity.Wallet); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.Wallet)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetbyUserId provides a mock function with given fields: ctx, id
func (_m *WalletRepository) GetbyUserId(ctx context.Context, id int64) ([]entity.Wallet, error) {
	ret := _m.Called(ctx, id)

	var r0 []entity.Wallet
	if rf, ok := ret.Get(0).(func(context.Context, int64) []entity.Wallet); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Wallet)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: ctx, w
func (_m *WalletRepository) Store(ctx context.Context, w entity.Wallet) error {
	ret := _m.Called(ctx, w)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Wallet) error); ok {
		r0 = rf(ctx, w)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, w
func (_m *WalletRepository) Update(ctx context.Context, w entity.Wallet) error {
	ret := _m.Called(ctx, w)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Wallet) error); ok {
		r0 = rf(ctx, w)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewWalletRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewWalletRepository creates a new instance of WalletRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWalletRepository(t mockConstructorTestingTNewWalletRepository) *WalletRepository {
	mock := &WalletRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
