app:
  name: 'wallet'
  version: '1.0.0'

http:
  port: '8080'

logger:
  log_level: 'debug'
  rollbar_env: 'wallet'

postgre:
  Db_max: 2
  url: 'postgres://wallet-user:12345@postgres:5432/postgres?sslmode=disable'

